### ISSUE TITLE
Fall: Ball geht ins Aus -> Start ab Mitte

### ISSUE THREAD

**Issue by OccamsBeard** [friedz/sonic-pong#2]
+ pong.rb
-> `bounce(x, y)` prüft paddle collisions

Es soll implementiert werden, dass im Fall `collision == nil` der Ball zurück in die Mitte gesetzt wird und der nächste Aufschlag stattfindet. 

#4 steht hiermit in Verbindung und kann bearbeitet werden, sobald das hier gelöst wurde.

**Comment by friedz** [comment]
ist erledigt
